Use 'make_file_id' and 'assert_file_grp_cardinality' throughout
OCR-D/ocrd_segment pull request #41
Opened 2020-08-07 15:42 UTC by kba

2020-08-07 15:43 UTC, kba commented
Unit tests would help, at least a smoke test to make sure there's no typos.

2020-08-14 17:56 UTC, bertsky commented
> Unit tests would help, at least a smoke test to make sure there's no typos.

True. I usually run pylint if I have nothing else.

Adapting to OCR-D/spec#164 OCR-D/core#530 and OCR-D/core#556 is harder in this repo, because it already used mixed fileGrps and document-global files (without pageId) before. I'll have to revisit some of the decisions made here. (@kba I'd be interested in your opinion about a good interface for `ocrd-segment-extract-pages` – see [here](https://github.com/OCR-D/ocrd_segment/pull/35#issuecomment-603577676) for explanation/discussion...)

2020-08-14 17:56 UTC, bertsky commented
> Unit tests would help, at least a smoke test to make sure there's no typos.

True. I usually run pylint if I have nothing else.

Adapting to OCR-D/spec#164 OCR-D/core#530 and OCR-D/core#556 is harder in this repo, because it already used mixed fileGrps and document-global files (without pageId) before. I'll have to revisit some of the decisions made here. (@kba I'd be interested in your opinion about a good interface for `ocrd-segment-extract-pages` – see [here](https://github.com/OCR-D/ocrd_segment/pull/35#issuecomment-603577676) for explanation/discussion...)

2020-08-21 09:57 UTC, bertsky requested changes

2020-08-21 09:57 UTC, bertsky commented on ocrd_segment/extract_pages.py
> +                LOG.info("No output file group for binarized images specified, falling back to output filegrp '%s'", bin_image_grp)
That's not correct. You moved `bin_image_grp` from second to third. Also, the error `"at most 3 output file grps allowed (raw, [binarized, [mask]] image)"` is missing.

I don't think this particular place is worth employing `assert_file_grp_cardinality` at all.

2020-08-21 09:57 UTC, bertsky commented on ocrd_segment/extract_pages.py
> +            pageId=input_file.pageId,
```suggestion
```

No, the COCO file runs across all pages, it mustn't have a `pageId`.

2020-08-21 09:57 UTC, bertsky commented on ocrd_segment/extract_pages.py
> +            pageId=input_file.pageId,
But you _should_ replace `pageId=page_id` with `pageId=input_file.pageId` on line 313 / 317...

2020-08-21 09:57 UTC, bertsky commented on ocrd_segment/import_image_segmentation.py
>          ifts = self.zip_input_files(ifgs) # input file tuples
Note: this is the method that should be encapsulated in core for multi-input page iteration...

2020-08-21 09:57 UTC, bertsky commented on ocrd_segment/replace_original.py
The docstring must be adapted here as well.

2020-08-21 11:38 UTC, kba commented on ocrd_segment/extract_pages.py
> +                LOG.info("No output file group for binarized images specified, falling back to output filegrp '%s'", bin_image_grp)
I thought it was elegant but I see your point. 3f31afa

2020-08-21 11:41 UTC, kba commented on ocrd_segment/extract_pages.py
> +            pageId=input_file.pageId,
5307199

2020-08-21 11:42 UTC, kba commented on ocrd_segment/import_image_segmentation.py
>          ifts = self.zip_input_files(ifgs) # input file tuples
you mean `zip_input_files`?

2020-08-21 11:43 UTC, kba commented on ocrd_segment/replace_original.py
176a280

2020-08-21 11:58 UTC, bertsky commented on ocrd_segment/import_image_segmentation.py
>          ifts = self.zip_input_files(ifgs) # input file tuples
Yes, that in combination with a loop over these file tuples instead of `Processor.input_files`. I have first seen that recipe in @finkf's ocrd-cis-align, then re-used it for ocrd-cor-asv-ann-evaluate and others. Would be great if this entered core (including error messages when some pages don't have files for all input fileGrps etc)...

2020-08-21 11:59 UTC, bertsky approved these changes
Thanks!

2020-08-21 12:03 UTC, kba commented on ocrd_segment/import_image_segmentation.py
>          ifts = self.zip_input_files(ifgs) # input file tuples
https://github.com/OCR-D/core/issues/568

2020-08-21 12:22 UTC, merged