added classes parameter to extract-region-processor; enables extracti…
OCR-D/ocrd_segment pull request #59
Opened 2022-05-13 11:28 UTC by JBBalling

…on of specific regions e.g. TableRegion

2022-05-13 13:07 UTC, bertsky requested changes
Great idea!

2022-05-13 13:07 UTC, bertsky commented on ocrd_segment/extract_regions.py
>                  if not name or name == 'Border' or ':' in name:
I'm afraid this stopped working after I added the sub-region types to `CLASSES` for the new drawing feature of extract-pages. – This is independent of your addition.
```suggestion
                if not name or not name.endswith("Region"):
```

2022-05-13 13:07 UTC, bertsky commented on ocrd_segment/extract_regions.py
> +                classes = {provided_classes: classes[provided_classes]}
```suggestion
            selected_classes = self.parameter["classes"].split(",")
            classes = { region: classes[region] for region in selected_classes }
```

2022-05-13 13:07 UTC, bertsky commented on ocrd_segment/ocrd-tool.json
> +            "TableRegion"
I'm afraid this does not work (and is not valid). With `enum` you enforce any if these values, but thereby also prohibit combining them with commas.

If you want to enforce this syntactically, you'd have to set `type=array`, and then place an `enum` on its `items`. (But then, of course, the code would have to be adapted as well (by removing comma-splitting).

```suggestion
```

2022-05-13 13:07 UTC, bertsky commented on ocrd_segment/ocrd-tool.json
> +          "description": "Comma-separated string of classes to extract e.g. 'TextRegion, TableRegion, ImageRegion'"
```suggestion
          "description": "Comma-separated string of region types to extract e.g. 'TextRegion,TableRegion,ImageRegion'. If empty, all regions are allowed."
```

2022-05-13 14:59 UTC, kba commented on ocrd_segment/ocrd-tool.json
> +          "enum": [
```suggestion
          "pattern": "((Noise|LineDrawing|Advert|Image|Chart|Music|Graphic|Unknown|Custom|Separator|Maths|Text|Map|Chem|Table)Region(,(Noise|LineDrawing|Advert|Image|Chart|Music|Graphic|Unknown|Custom|Separator|Maths|Text|Map|Chem|Table)Region)*)?" 
```

:)

2022-05-13 15:14 UTC, bertsky commented on ocrd_segment/ocrd-tool.json
> +          "enum": [
Oh, fascinating! Does the JSON parser really enforce this?

2022-05-13 15:27 UTC, kba commented on ocrd_segment/ocrd-tool.json
> +          "enum": [
Yes, `pattern` is generally enforced. Whether it's sensible is another question, the resulting error message won't be very intuitive for the user.

2022-05-16 16:25 UTC, bertsky approved these changes
Excellent, thanks!

2022-05-16 16:26 UTC, merged